name: self-test
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build-only-docker:
    uses: ./.github/workflows/dockerfile-build-and-push.yml
    with:
      env: dev
      service_slug: selftest-dummy
      dockerfile: selftest/Dockerfile
      context: selftest
      push: false
