name: self-test
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build-only-docker:
    uses: ./.github/workflows/dockerfile-build-and-push.yml
    with:
      env: dev
      service_slug: selftest-dummy
      dockerfile: selftest/Dockerfile
      context: selftest
      push: false

  build-only-static:
    uses: ./.github/workflows/static-publish-to-s3.yml
    with:
      env: dev
      working-directory: selftest/spa
      build-command: npm run build
      build-output-dir: dist
      s3-bucket: openworks-dev-actions-selftest
      publish: false
